// Verified research papers for the Voter Education and Voter Turnout wiki.
// Each entry: slug, short (link text), title, citation, url, year, summary,
// theme (for the overview grouping), and contributions [{topic, note}].
// Topic slugs must match a page under src/content/docs/.

export const TOPIC_LABELS = {
  'interventions/overview': 'Interventions Overview',
  'interventions/door-to-door-canvassing': 'Door-to-Door Canvassing',
  'interventions/direct-mail': 'Direct Mail',
  'interventions/phone-banking': 'Phone Banking and Calls',
  'interventions/text-messaging': 'Text Messaging (SMS)',
  'interventions/social-pressure-messaging': 'Social Pressure and Social Norms',
  'interventions/voter-guides-and-information': 'Voter Guides and Information',
  'interventions/digital-and-social-media-ads': 'Digital and Social Media Ads',
  'interventions/school-based-civic-education': 'School-Based Civic Education',
  'policy-approaches/overview': 'Policy Approaches Overview',
  'policy-approaches/automatic-voter-registration': 'Automatic Voter Registration',
  'policy-approaches/civic-education-mandates': 'Civic Education Mandates',
  'policy-approaches/vote-by-mail-and-ballot-access': 'Vote-by-Mail and Ballot Access',
  'policy-approaches/compulsory-voting': 'Compulsory Voting',
  'key-debates/voluntary-vs-mandatory': 'Voluntary vs. Mandatory Voting',
  'key-debates/information-vs-mobilization': 'Information vs. Mobilization',
  'key-debates/informed-voting-vs-turnout': 'Informed Voting vs. Maximum Turnout',
  'key-debates/partisan-effects': 'Partisan Effects',
};

export const THEMES = [
  'GOTV field experiments',
  'Digital outreach & persuasion',
  'Compulsory voting & representation',
  'Civic education & youth',
  'Information & vote choice',
  'Registration, access & partisan effects',
];

export const PAPERS = [
  // ===== Theme 1: GOTV field experiments =====
  {
    slug: 'gerber-green-2000-canvassing-phone-mail',
    short: 'Gerber & Green (2000)',
    title: 'Gerber & Green (2000): Canvassing, Telephone Calls, and Direct Mail',
    citation: 'Gerber, Alan S., and Donald P. Green. 2000. "The Effects of Canvassing, Telephone Calls, and Direct Mail on Voter Turnout: A Field Experiment." American Political Science Review 94(3): 653–663.',
    url: 'https://doi.org/10.2307/2585837',
    year: 2000,
    theme: 'GOTV field experiments',
    summary: 'A randomized nonpartisan GOTV field experiment on roughly 30,000 registered voters in New Haven, CT before the 1998 election, comparing door-to-door canvassing, direct mail, and commercial phone calls. Face-to-face canvassing raised turnout by about 8–10 points, direct mail had small effects (about 0.5 point per mailer), and professional phone calls had no detectable effect. The study launched the modern GOTV field-experiment paradigm.',
    contributions: [
      { topic: 'interventions/overview', note: 'foundational modern GOTV field experiment establishing the randomized-experiment methodology for comparing mobilization tactics' },
      { topic: 'interventions/door-to-door-canvassing', note: 'core evidence that personal canvassing is the most effective mobilization mode (~8-point boost)' },
      { topic: 'interventions/direct-mail', note: 'shows direct mail has small but measurable per-piece turnout effects' },
      { topic: 'interventions/phone-banking', note: 'finds impersonal commercial phone banks ineffective, setting up the later call-quality debate' },
      { topic: 'key-debates/information-vs-mobilization', note: 'demonstrates turnout gains from mobilization independent of new political information' },
    ],
  },
  {
    slug: 'green-gerber-nickerson-2003-local-elections-canvassing',
    short: 'Green, Gerber & Nickerson (2003)',
    title: 'Green, Gerber & Nickerson (2003): Canvassing in Local Elections',
    citation: 'Green, Donald P., Alan S. Gerber, and David W. Nickerson. 2003. "Getting Out the Vote in Local Elections: Results from Six Door-to-Door Canvassing Experiments." The Journal of Politics 65(4): 1083–1096.',
    url: 'https://doi.org/10.1111/1468-2508.t01-1-00126',
    year: 2003,
    theme: 'GOTV field experiments',
    summary: 'Six randomized nonpartisan door-to-door canvassing experiments run by student and community coalitions before the November 2001 local elections in Bridgeport, Columbus, Detroit, Minneapolis, Raleigh, and St. Paul. Face-to-face canvassing significantly increased turnout across diverse low-salience local contexts, replicating the New Haven canvassing result.',
    contributions: [
      { topic: 'interventions/door-to-door-canvassing', note: 'multi-site replication confirming canvassing effectiveness across varied local elections' },
      { topic: 'interventions/overview', note: 'demonstrates external validity and replicability of GOTV field-experiment findings' },
    ],
  },
  {
    slug: 'nickerson-2006-volunteer-phone-calls',
    short: 'Nickerson (2006)',
    title: 'Nickerson (2006): Volunteer Phone Calls Can Increase Turnout',
    citation: 'Nickerson, David W. 2006. "Volunteer Phone Calls Can Increase Turnout: Evidence from Eight Field Experiments." American Politics Research 34(3): 271–292.',
    url: 'https://doi.org/10.1177/1532673X05275923',
    year: 2006,
    theme: 'GOTV field experiments',
    summary: 'Pooled eight randomized nonpartisan volunteer phone-bank experiments across six cities in 2000–2001. Volunteer calls raised turnout by about 3.8 percentage points and were cost-competitive with canvassing (roughly one additional vote per $26), challenging the earlier finding that phone calls do not work.',
    contributions: [
      { topic: 'interventions/phone-banking', note: 'evidence that personal, high-quality volunteer calls do increase turnout, revising the null phone-call finding' },
      { topic: 'key-debates/information-vs-mobilization', note: 'shows the personal touch, not information content, drives phone-call effectiveness' },
    ],
  },
  {
    slug: 'nickerson-2007-quality-is-job-one-phone',
    short: 'Nickerson (2007)',
    title: 'Nickerson (2007): Quality Is Job One',
    citation: 'Nickerson, David W. 2007. "Quality Is Job One: Professional and Volunteer Voter Mobilization Calls." American Journal of Political Science 51(2): 269–282.',
    url: 'https://doi.org/10.1111/j.1540-5907.2007.00250.x',
    year: 2007,
    theme: 'GOTV field experiments',
    summary: 'Directly compares professional (commercial) and volunteer phone banks in randomized experiments, isolating call quality as the key variable. Unhurried, personal, high-quality calls raise turnout regardless of caller type, explaining why perfunctory commercial calls fail while engaged volunteer calls succeed.',
    contributions: [
      { topic: 'interventions/phone-banking', note: 'establishes call quality/personalization as the decisive moderator of phone-bank effectiveness' },
      { topic: 'key-debates/information-vs-mobilization', note: 'reinforces that manner of contact, not information, produces mobilization' },
    ],
  },
  {
    slug: 'nickerson-2008-is-voting-contagious',
    short: 'Nickerson (2008)',
    title: 'Nickerson (2008): Is Voting Contagious?',
    citation: 'Nickerson, David W. 2008. "Is Voting Contagious? Evidence from Two Field Experiments." American Political Science Review 102(1): 49–57.',
    url: 'https://doi.org/10.1017/S0003055408080039',
    year: 2008,
    theme: 'GOTV field experiments',
    summary: 'Uses a placebo-controlled door-to-door design in two-voter households, where the answerer received either a GOTV or a recycling (placebo) pitch, to measure within-household spillover. About 60% of the turnout effect of canvassing was passed to the other household member, demonstrating contagion of voting behavior.',
    contributions: [
      { topic: 'interventions/door-to-door-canvassing', note: 'shows canvassing effects spill over within households, amplifying its per-contact impact' },
      { topic: 'interventions/social-pressure-messaging', note: 'provides a mechanism (interpersonal transmission) linking contact to social influence' },
    ],
  },
  {
    slug: 'gerber-green-larimer-2008-social-pressure',
    short: 'Gerber, Green & Larimer (2008)',
    title: 'Gerber, Green & Larimer (2008): Social Pressure and Voter Turnout',
    citation: 'Gerber, Alan S., Donald P. Green, and Christopher W. Larimer. 2008. "Social Pressure and Voter Turnout: Evidence from a Large-Scale Field Experiment." American Political Science Review 102(1): 33–48.',
    url: 'https://doi.org/10.1017/S000305540808009X',
    year: 2008,
    theme: 'GOTV field experiments',
    summary: 'A randomized experiment mailing ~180,000 Michigan households four messages varying in social pressure before the 2006 primary. Turnout rose from 29.7% (control) to 31.5% (civic duty), 32.2% (Hawthorne/"being studied"), 34.5% (self-history "Your Neighbors"), and 37.6% (disclosing the household\'s and neighbors\' voting records) — an ~8-point effect for the strongest mailer, among the largest mail effects ever recorded.',
    contributions: [
      { topic: 'interventions/social-pressure-messaging', note: 'landmark demonstration that social-pressure mail dramatically boosts turnout, scaling with pressure intensity' },
      { topic: 'interventions/direct-mail', note: 'shows mail can produce very large effects when it applies social pressure' },
      { topic: 'key-debates/information-vs-mobilization', note: 'evidence that normative/social incentives, not information, drive the effect' },
    ],
  },
  {
    slug: 'dale-strauss-2009-text-message-reminders',
    short: 'Dale & Strauss (2009)',
    title: "Dale & Strauss (2009): Don't Forget to Vote",
    citation: 'Dale, Allison, and Aaron Strauss. 2009. "Don\'t Forget to Vote: Text Message Reminders as a Mobilization Tool." American Journal of Political Science 53(4): 787–804.',
    url: 'https://doi.org/10.1111/j.1540-5907.2009.00401.x',
    year: 2009,
    theme: 'GOTV field experiments',
    summary: 'A nationwide randomized field experiment (n ≈ 8,053) delivering Election Day SMS reminders in 2006. Text reminders raised turnout by about 3.0 percentage points at very low cost, and the authors argue impersonal but noticeable reminders can mobilize without social connectedness (a "noticeable reminder" theory).',
    contributions: [
      { topic: 'interventions/text-messaging', note: 'foundational experiment establishing SMS reminders as a cost-effective mobilization tool' },
      { topic: 'key-debates/information-vs-mobilization', note: 'supports a reminder/salience mechanism distinct from personal social connection' },
    ],
  },
  {
    slug: 'panagopoulos-2010-pride-shame',
    short: 'Panagopoulos (2010)',
    title: 'Panagopoulos (2010): Pride, Shame and Publicizing Voting',
    citation: 'Panagopoulos, Costas. 2010. "Affect, Social Pressure and Prosocial Motivation: Field Experimental Evidence of the Mobilizing Effects of Pride, Shame and Publicizing Voting Behavior." Political Behavior 32(3): 369–386.',
    url: 'https://doi.org/10.1007/s11109-010-9114-0',
    year: 2010,
    theme: 'GOTV field experiments',
    summary: 'Three field experiments in the November 2007 elections tested mailings threatening to publicize voters\' turnout — honoring voters ("pride") or shaming abstainers ("shame") by listing names in the local newspaper. Both pride and shame appeals significantly increased turnout, extending the social-pressure findings to affect-based prosocial motivation.',
    contributions: [
      { topic: 'interventions/social-pressure-messaging', note: 'shows pride- and shame-based publicity appeals both mobilize, refining social-pressure mail design' },
      { topic: 'interventions/direct-mail', note: 'additional evidence on how message framing conditions mail effectiveness' },
    ],
  },
  {
    slug: 'nickerson-rogers-2010-voting-plan',
    short: 'Nickerson & Rogers (2010)',
    title: 'Nickerson & Rogers (2010): Do You Have a Voting Plan?',
    citation: 'Nickerson, David W., and Todd Rogers. 2010. "Do You Have a Voting Plan? Implementation Intentions, Voter Turnout, and Organic Plan Making." Psychological Science 21(2): 194–199.',
    url: 'https://doi.org/10.1177/0956797609359326',
    year: 2010,
    theme: 'GOTV field experiments',
    summary: 'A large randomized phone-call experiment (~287,000 contacts) in the 2008 presidential primary tested scripts that helped voters form a concrete "voting plan" (when, from where, what they\'ll be doing before). Plan-making calls increased turnout more than standard GOTV calls, especially in single-eligible-voter households, showing script content shapes call effectiveness.',
    contributions: [
      { topic: 'interventions/phone-banking', note: 'shows implementation-intention ("voting plan") scripts outperform standard GOTV phone scripts' },
      { topic: 'interventions/overview', note: 'introduces psychological plan-making as a scalable mechanism to boost mobilization effects' },
    ],
  },
  {
    slug: 'malhotra-michelson-rogers-valenzuela-2011-text-messages',
    short: 'Malhotra et al. (2011)',
    title: 'Malhotra et al. (2011): Text Messages as Mobilization Tools',
    citation: 'Malhotra, Neil, Melissa R. Michelson, Todd Rogers, and Ali Adam Valenzuela. 2011. "Text Messages as Mobilization Tools: Implications for Theories of Political Participation." American Politics Research 39(4): 664–681.',
    url: 'https://doi.org/10.1177/1532673X11398949',
    year: 2011,
    theme: 'GOTV field experiments',
    summary: 'A field experiment testing "cold" text messages (with no prior personal contact or opt-in interaction). Even auxiliary-interaction-free texts significantly boosted turnout, challenging the claim that social connectedness is necessary for mobilization and reinforcing a salience/reminder mechanism.',
    contributions: [
      { topic: 'interventions/text-messaging', note: 'demonstrates standalone "cold" SMS still mobilizes, strengthening the case for low-cost texting' },
      { topic: 'key-debates/information-vs-mobilization', note: 'evidence that a noticeable prompt, not social connection or information, can suffice' },
    ],
  },
  {
    slug: 'green-mcgrath-aronow-2013-field-experiments-review',
    short: 'Green, McGrath & Aronow (2013)',
    title: 'Green, McGrath & Aronow (2013): Field Experiments and Voter Turnout',
    citation: 'Green, Donald P., Mary C. McGrath, and Peter M. Aronow. 2013. "Field Experiments and the Study of Voter Turnout." Journal of Elections, Public Opinion and Parties 23(1): 27–48.',
    url: 'https://doi.org/10.1080/17457289.2012.728223',
    year: 2013,
    theme: 'GOTV field experiments',
    summary: 'A synthesizing review and meta-analytic summary of the GOTV field-experiment literature, reporting average treatment effects by contact mode (door-to-door canvassing, direct mail, robocalls/live calls, and text messages). It confirms canvassing and personal contact as most effective, mail and calls as modest, and organizes the field into tactic-testing versus social-psychological-theory-testing strands.',
    contributions: [
      { topic: 'interventions/overview', note: 'meta-analytic benchmark of average effect sizes across all major personal-contact GOTV modes' },
      { topic: 'interventions/door-to-door-canvassing', note: 'quantifies canvassing as the highest-impact mode across studies' },
      { topic: 'interventions/phone-banking', note: 'summarizes modest average effects of calls, moderated by quality' },
      { topic: 'interventions/direct-mail', note: 'aggregates small average mail effects across many experiments' },
      { topic: 'interventions/text-messaging', note: 'pools SMS experiments into an average mobilization estimate' },
    ],
  },
  {
    slug: 'green-gerber-get-out-the-vote-book',
    short: 'Green & Gerber (Get Out the Vote)',
    title: 'Green & Gerber: Get Out the Vote',
    citation: 'Green, Donald P., and Alan S. Gerber. Get Out the Vote: How to Increase Voter Turnout. Washington, DC: Brookings Institution Press. (1st ed. 2004; later editions 2008, 2015, 2019, 2024.)',
    url: 'https://www.brookings.edu/books/get-out-the-vote-2/',
    year: 2019,
    theme: 'GOTV field experiments',
    summary: 'The authoritative practitioner-oriented synthesis of GOTV field-experiment evidence, translating dozens of randomized studies into cost-per-vote guidance across canvassing, mail, phone, email, and text. It ranks door-to-door canvassing and personal contact as most effective and reports comparative cost-effectiveness for each tactic.',
    contributions: [
      { topic: 'interventions/overview', note: 'comprehensive synthesis and cost-per-vote comparison of all major mobilization tactics' },
      { topic: 'interventions/door-to-door-canvassing', note: 'summarizes evidence and best practices for canvassing' },
      { topic: 'interventions/direct-mail', note: 'reviews when and how mail (including social-pressure mail) works' },
      { topic: 'interventions/phone-banking', note: 'consolidates evidence on volunteer vs. commercial calls and call quality' },
      { topic: 'interventions/text-messaging', note: 'summarizes SMS mobilization evidence and cost-effectiveness' },
    ],
  },

  // ===== Theme 2: Digital outreach & persuasion =====
  {
    slug: 'bond-2012-61-million-person-experiment',
    short: 'Bond et al. (2012)',
    title: 'Bond et al. (2012): A 61-Million-Person Experiment',
    citation: 'Bond, Robert M., Christopher J. Fariss, Jason J. Jones, Adam D. I. Kramer, Cameron Marlow, Jaime E. Settle, and James H. Fowler. 2012. "A 61-Million-Person Experiment in Social Influence and Political Mobilization." Nature 489(7415): 295–298.',
    url: 'https://doi.org/10.1038/nature11421',
    year: 2012,
    theme: 'Digital outreach & persuasion',
    summary: 'A randomized experiment delivered get-out-the-vote messages to 61 million Facebook users on Election Day 2010, comparing an informational message, a "social" message showing friends who had voted, and a control. The social message increased turnout directly (~60,000 votes) and, via social contagion among close friends, indirectly (~280,000 votes), for roughly 340,000 additional votes; the social-transmission effect exceeded the direct message effect.',
    contributions: [
      { topic: 'interventions/digital-and-social-media-ads', note: 'flagship large-scale experiment showing social-media civic nudges can mobilize turnout' },
      { topic: 'interventions/social-pressure-messaging', note: 'demonstrates the "social" (peer-visibility) message outperforms a purely informational one' },
      { topic: 'key-debates/information-vs-mobilization', note: 'evidence that mobilization framing plus social cues, not information alone, drives turnout' },
    ],
  },
  {
    slug: 'jones-2017-social-influence-2012-election',
    short: 'Jones et al. (2017)',
    title: 'Jones et al. (2017): Social Influence in the 2012 Election',
    citation: 'Jones, Jason J., Robert M. Bond, Eytan Bakshy, Dean Eckles, and James H. Fowler. 2017. "Social Influence and Political Mobilization: Further Evidence From a Randomized Experiment in the 2012 U.S. Presidential Election." PLOS ONE 12(4): e0173851.',
    url: 'https://doi.org/10.1371/journal.pone.0173851',
    year: 2017,
    theme: 'Digital outreach & persuasion',
    summary: 'A replication of the Facebook mobilization experiment during the higher-salience 2012 presidential election. Despite the expectation of smaller effects in high-stakes elections, the social message significantly increased voting among recipients and also increased turnout among their close friends, with the total spillover effect likely larger than the direct effect.',
    contributions: [
      { topic: 'interventions/digital-and-social-media-ads', note: 'replicates social-media mobilization effects in a presidential-year context' },
      { topic: 'interventions/social-pressure-messaging', note: 'confirms peer-visibility cues generate contagion-based turnout gains' },
      { topic: 'key-debates/information-vs-mobilization', note: 'reinforces that social mobilization cues, not information, produce the effect' },
    ],
  },
  {
    slug: 'broockman-green-2014-online-advertisements-name-recognition',
    short: 'Broockman & Green (2014)',
    title: 'Broockman & Green (2014): Do Online Ads Increase Name Recognition?',
    citation: 'Broockman, David E., and Donald P. Green. 2014. "Do Online Advertisements Increase Political Candidates\' Name Recognition or Favorability? Evidence from Randomized Field Experiments." Political Behavior 36(2): 263–289.',
    url: 'https://doi.org/10.1007/s11109-013-9239-z',
    year: 2014,
    theme: 'Digital outreach & persuasion',
    summary: 'Two field experiments randomly targeted constituents with high-volume Facebook advertising for candidates, then measured recall, name recognition, and favorability via ostensibly unrelated phone surveys. Exposed voters were in some cases more likely to recall ads but no more likely to recognize or positively evaluate the candidates, providing early evidence that online display ads have minimal persuasive/awareness effects.',
    contributions: [
      { topic: 'interventions/digital-and-social-media-ads', note: 'early rigorous null on the persuasive/recognition effects of online display ads' },
      { topic: 'key-debates/information-vs-mobilization', note: 'shows digital ad exposure did not translate into changed candidate evaluations' },
    ],
  },
  {
    slug: 'kalla-broockman-2018-minimal-persuasive-effects',
    short: 'Kalla & Broockman (2018)',
    title: 'Kalla & Broockman (2018): The Minimal Persuasive Effects of Campaign Contact',
    citation: 'Kalla, Joshua L., and David E. Broockman. 2018. "The Minimal Persuasive Effects of Campaign Contact in General Elections: Evidence from 49 Field Experiments." American Political Science Review 112(1): 148–166.',
    url: 'https://doi.org/10.1017/S0003055417000363',
    year: 2018,
    theme: 'Digital outreach & persuasion',
    summary: 'A meta-analysis of 40 field experiments plus nine new original experiments finds the best estimate of the average effect of campaign contact and advertising on candidate choice in general elections is approximately zero. Persuasive effects can appear earlier in campaigns, in primaries/ballot measures, or when messaging engages unfamiliar issues, but general-election persuasion via contact and ads is minimal.',
    contributions: [
      { topic: 'key-debates/information-vs-mobilization', note: 'cornerstone "minimal effects" statement distinguishing persuasion from mobilization' },
      { topic: 'interventions/overview', note: 'synthesizes the persuasive impact of contact and advertising across many interventions' },
      { topic: 'interventions/digital-and-social-media-ads', note: 'includes advertising among channels found to have near-zero general-election persuasion' },
      { topic: 'interventions/door-to-door-canvassing', note: 'canvassing among the contact modes estimated to have minimal persuasive (as opposed to mobilizing) effect' },
    ],
  },
  {
    slug: 'coppock-hill-vavreck-2020-small-effects-advertising',
    short: 'Coppock, Hill & Vavreck (2020)',
    title: 'Coppock, Hill & Vavreck (2020): The Small Effects of Political Advertising',
    citation: 'Coppock, Alexander, Seth J. Hill, and Lynn Vavreck. 2020. "The Small Effects of Political Advertising Are Small Regardless of Context, Message, Sender, or Receiver: Evidence from 59 Real-Time Randomized Experiments." Science Advances 6(36): eabc4046.',
    url: 'https://doi.org/10.1126/sciadv.abc4046',
    year: 2020,
    theme: 'Digital outreach & persuasion',
    summary: 'Across 59 real-time survey experiments testing 49 different 2016 presidential ads on ~34,000 people over 29 weeks, political ads produced small average persuasive effects (roughly 0.05 points on a 100-point candidate-support scale). Effects were consistently small regardless of party, message, prior beliefs, or timing, undercutting the "heterogeneity" explanation that ads work well in specific circumstances.',
    contributions: [
      { topic: 'interventions/digital-and-social-media-ads', note: 'large evidence base that advertising persuasion is uniformly small' },
      { topic: 'key-debates/information-vs-mobilization', note: 'supports the minimal-persuasion view of campaign messaging' },
      { topic: 'key-debates/partisan-effects', note: 'shows small effects hold across partisan senders and receivers' },
    ],
  },
  {
    slug: 'coppock-green-porter-2022-digital-advertising-vote-choice',
    short: 'Coppock, Green & Porter (2022)',
    title: 'Coppock, Green & Porter (2022): Does Digital Advertising Affect Vote Choice?',
    citation: 'Coppock, Alexander, Donald P. Green, and Ethan Porter. 2022. "Does Digital Advertising Affect Vote Choice? Evidence from a Randomized Field Experiment." Research & Politics 9(1): 1–8.',
    url: 'https://doi.org/10.1177/20531680221076901',
    year: 2022,
    theme: 'Digital outreach & persuasion',
    summary: 'A ZIP-code-level randomized field experiment ran Democratic-leaning Facebook/Instagram ads (seen 1.1+ million times) during the 2018 Florida midterms. Estimated effects on Democratic vote share were essentially zero (−0.04 percentage points, SE 0.85), reinforcing that digital advertising has minimal persuasive effect on vote choice in competitive races.',
    contributions: [
      { topic: 'interventions/digital-and-social-media-ads', note: 'field (behavioral, not survey) null on digital ad persuasion of actual vote share' },
      { topic: 'key-debates/information-vs-mobilization', note: 'evidence that digital ad exposure does not shift electoral outcomes' },
      { topic: 'key-debates/partisan-effects', note: 'partisan-targeted ads failed to move partisan vote share' },
    ],
  },
  {
    slug: 'aggarwal-2023-campaign-wide-digital-advertising-turnout',
    short: 'Aggarwal et al. (2023)',
    title: 'Aggarwal et al. (2023): Campaign-Wide Digital Advertising and Turnout',
    citation: 'Aggarwal, Minali, Jennifer Allen, Alexander Coppock, Dan Frankowski, Solomon Messing, Kelly Zhang, James Barnes, Andrew Beasley, Harry Hantman, and Sylvan Zheng. 2023. "A 2 Million-Person, Campaign-Wide Field Experiment Shows How Digital Advertising Affects Voter Turnout." Nature Human Behaviour 7(3): 332–341.',
    url: 'https://doi.org/10.1038/s41562-022-01487-4',
    year: 2023,
    theme: 'Digital outreach & persuasion',
    summary: 'An $8.9 million, 8-month social-media advertising program targeted ~2 million persuadable voters in five battleground states during the 2020 US presidential election, aiming to boost anti-Trump/pro-Biden turnout. The program produced no detectable average effect on turnout, providing a large-scale behavioral null for digital mobilization advertising.',
    contributions: [
      { topic: 'interventions/digital-and-social-media-ads', note: 'largest campaign-wide field test showing near-zero average turnout effect of digital ads' },
      { topic: 'key-debates/information-vs-mobilization', note: 'digital advertising did not mobilize turnout at scale' },
      { topic: 'interventions/overview', note: 'benchmark for the limited real-world impact of paid digital outreach' },
    ],
  },
  {
    slug: 'broockman-kalla-2016-durably-reducing-transphobia',
    short: 'Broockman & Kalla (2016)',
    title: 'Broockman & Kalla (2016): Durably Reducing Transphobia',
    citation: 'Broockman, David, and Joshua Kalla. 2016. "Durably Reducing Transphobia: A Field Experiment on Door-to-Door Canvassing." Science 352(6282): 220–224.',
    url: 'https://doi.org/10.1126/science.aad9713',
    year: 2016,
    theme: 'Digital outreach & persuasion',
    summary: 'In a randomized field experiment, 56 canvassers held ~10-minute perspective-taking ("deep canvassing") conversations with 501 voters in South Florida about transgender rights. A single conversation markedly reduced anti-transgender prejudice, with effects persisting at least three months and exceeding the average decline in US homophobia from 1998–2012.',
    contributions: [
      { topic: 'interventions/door-to-door-canvassing', note: 'foundational deep-canvassing experiment showing durable attitude change via face-to-face conversation' },
      { topic: 'key-debates/information-vs-mobilization', note: 'demonstrates persuasion (attitude change) is achievable through interpersonal, non-argumentative contact' },
      { topic: 'interventions/overview', note: 'landmark for persuasion-via-conversation as a distinct mechanism from turnout mobilization' },
    ],
  },
  {
    slug: 'kalla-broockman-2020-reducing-exclusionary-attitudes',
    short: 'Kalla & Broockman (2020)',
    title: 'Kalla & Broockman (2020): Reducing Exclusionary Attitudes',
    citation: 'Kalla, Joshua L., and David E. Broockman. 2020. "Reducing Exclusionary Attitudes Through Interpersonal Conversation: Evidence from Three Field Experiments." American Political Science Review 114(2): 410–425.',
    url: 'https://doi.org/10.1017/S0003055419000923',
    year: 2020,
    theme: 'Digital outreach & persuasion',
    summary: 'Three pre-registered field experiments (230 canvassers, 6,869 voters, 7 US locations) tested deep canvassing on attitudes toward unauthorized immigrants and transgender people. Argument-only conversations had no effect, but conversations adding non-judgmental exchange of personal narratives durably reduced exclusionary attitudes for at least four months, supporting the scalability of the approach.',
    contributions: [
      { topic: 'interventions/door-to-door-canvassing', note: 'establishes narrative exchange (not argumentation) as the active ingredient in deep canvassing, and shows replicability' },
      { topic: 'key-debates/information-vs-mobilization', note: 'argument-only (informational) contact failed while perspective-taking succeeded' },
      { topic: 'interventions/overview', note: 'reinforces interpersonal conversation as a durable persuasion tool' },
    ],
  },
  {
    slug: 'hersh-2015-hacking-the-electorate',
    short: 'Hersh (2015)',
    title: 'Hersh (2015): Hacking the Electorate',
    citation: 'Hersh, Eitan D. 2015. Hacking the Electorate: How Campaigns Perceive Voters. New York: Cambridge University Press.',
    url: 'https://doi.org/10.1017/CBO9781316212783',
    year: 2015,
    theme: 'Digital outreach & persuasion',
    summary: 'Hersh argues that campaigns\' microtargeting is constrained by the public records (voter files, administrative data) available in each state, so campaigns act on "perceived voters" — data avatars rather than real people. Because states collect different records, campaign targeting and mobilization coalitions vary across the country, and microtargeting is far cruder than commonly assumed.',
    contributions: [
      { topic: 'interventions/digital-and-social-media-ads', note: 'explains the data infrastructure and limits behind microtargeted digital outreach' },
      { topic: 'interventions/overview', note: 'foundational account of how campaigns select and reach voters for contact' },
      { topic: 'key-debates/partisan-effects', note: 'shows how data availability shapes which (often partisan) voters campaigns mobilize' },
    ],
  },

  // ===== Theme 3: Compulsory voting & representation =====
  {
    slug: 'lijphart-1997-unequal-participation',
    short: 'Lijphart (1997)',
    title: 'Lijphart (1997): Unequal Participation',
    citation: 'Lijphart, Arend. 1997. "Unequal Participation: Democracy\'s Unresolved Dilemma. Presidential Address, American Political Science Association, 1996." American Political Science Review 91(1): 1–14.',
    url: 'https://doi.org/10.2307/2952255',
    year: 1997,
    theme: 'Compulsory voting & representation',
    summary: 'Landmark presidential address arguing that low turnout is systematically class-biased — less well-off citizens vote less — so unequal turnout produces unequal political influence, a fundamental democratic problem. Lijphart proposes institutional fixes to maximize turnout, most powerfully compulsory voting, and frames the "who votes matters" agenda that defines this literature.',
    contributions: [
      { topic: 'key-debates/voluntary-vs-mandatory', note: 'foundational normative case that compulsory voting is the most effective remedy for class-biased turnout' },
      { topic: 'policy-approaches/compulsory-voting', note: 'canonical argument that mandatory voting equalizes participation and political influence' },
      { topic: 'policy-approaches/overview', note: 'establishes turnout inequality as the central rationale for pro-turnout institutional reform' },
    ],
  },
  {
    slug: 'fowler-2013-electoral-policy-consequences-turnout',
    short: 'Fowler (2013)',
    title: 'Fowler (2013): Electoral and Policy Consequences of Turnout',
    citation: 'Fowler, Anthony. 2013. "Electoral and Policy Consequences of Voter Turnout: Evidence from Compulsory Voting in Australia." Quarterly Journal of Political Science 8(2): 159–182.',
    url: 'https://doi.org/10.1561/100.00012055',
    year: 2013,
    theme: 'Compulsory voting & representation',
    summary: 'Uses the staggered adoption of compulsory voting across Australian states as a natural experiment, showing it raised turnout by ~24 points and increased Labor (left) vote and seat shares by 7–10 points. Australia\'s adoption also significantly raised pension spending — direct evidence that higher turnout shifts both election and policy outcomes.',
    contributions: [
      { topic: 'policy-approaches/compulsory-voting', note: 'causal estimate that compulsory voting sharply raises turnout and reshapes electoral outcomes' },
      { topic: 'key-debates/partisan-effects', note: 'strong evidence that higher turnout can benefit left/labor parties' },
      { topic: 'policy-approaches/overview', note: 'demonstrates turnout affects downstream policy (pension spending), not just vote shares' },
    ],
  },
  {
    slug: 'bechtel-hangartner-schmid-2016-leftist-policy',
    short: 'Bechtel, Hangartner & Schmid (2016)',
    title: 'Bechtel, Hangartner & Schmid (2016): Compulsory Voting and Leftist Policy',
    citation: 'Bechtel, Michael M., Dominik Hangartner, and Lukas Schmid. 2016. "Does Compulsory Voting Increase Support for Leftist Policy?" American Journal of Political Science 60(3): 752–767.',
    url: 'https://doi.org/10.1111/ajps.12224',
    year: 2016,
    theme: 'Compulsory voting & representation',
    summary: 'Exploits sanctioned compulsory voting in the Swiss canton of Vaud (1900–1970), finding it raised turnout in federal referendums by ~30 points. The mobilization of lower-income citizens translated into up to 20 points greater electoral support for leftist policy positions.',
    contributions: [
      { topic: 'policy-approaches/compulsory-voting', note: 'quasi-experimental evidence that mandatory voting boosts turnout and shifts referendum outcomes leftward' },
      { topic: 'key-debates/partisan-effects', note: 'shows compulsion changes policy preferences expressed at the ballot, favoring left positions' },
      { topic: 'policy-approaches/overview', note: 'links turnout inequality to substantive policy representation' },
    ],
  },
  {
    slug: 'brennan-hill-2014-compulsory-voting-for-and-against',
    short: 'Brennan & Hill (2014)',
    title: 'Brennan & Hill (2014): Compulsory Voting: For and Against',
    citation: 'Brennan, Jason, and Lisa Hill. 2014. Compulsory Voting: For and Against. Cambridge: Cambridge University Press.',
    url: 'https://doi.org/10.1017/CBO9781139649742',
    year: 2014,
    theme: 'Compulsory voting & representation',
    summary: 'A structured debate book: Brennan argues compulsory voting is an unjust violation of liberty that may worsen decision quality, while Hill defends it as a reasonable imposition that produces more legitimate, representative high-turnout elections. The definitive normative treatment of the mandatory-voting debate.',
    contributions: [
      { topic: 'key-debates/voluntary-vs-mandatory', note: 'the central paired argument for and against compulsion' },
      { topic: 'policy-approaches/compulsory-voting', note: 'comprehensive normative and empirical assessment of the policy' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'engages whether compelling uninformed citizens to vote improves or degrades outcomes' },
    ],
  },
  {
    slug: 'singh-2021-beyond-turnout',
    short: 'Singh (2021)',
    title: 'Singh (2021): Beyond Turnout',
    citation: 'Singh, Shane P. 2021. Beyond Turnout: How Compulsory Voting Shapes Citizens and Political Parties. Oxford: Oxford University Press.',
    url: 'https://doi.org/10.1093/oso/9780198832928.001.0001',
    year: 2021,
    theme: 'Compulsory voting & representation',
    summary: 'Comprehensive treatment showing compulsory voting\'s effects reach "beyond turnout": compelled voters are less likely to base choices on ideology or issue positions, satisfaction with democracy is altered, and parties shift toward programmatic (away from clientelistic) strategies. Argues mandatory voting reshapes citizen attitudes and vote choice, not just participation rates.',
    contributions: [
      { topic: 'policy-approaches/compulsory-voting', note: 'synthesizes evidence on how compulsion changes voters and parties beyond raising turnout' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'shows compelled voters vote less on ideology/information, central to the quality-vs-turnout debate' },
      { topic: 'key-debates/voluntary-vs-mandatory', note: 'weighs downstream attitudinal and party-strategy consequences of compulsion' },
    ],
  },
  {
    slug: 'hoffman-leon-lombardi-2017-compulsory-voting-austria',
    short: 'Hoffman, León & Lombardi (2017)',
    title: 'Hoffman, León & Lombardi (2017): Compulsory Voting and Government Spending',
    citation: 'Hoffman, Mitchell, Gianmarco León, and María Lombardi. 2017. "Compulsory Voting, Turnout, and Government Spending: Evidence from Austria." Journal of Public Economics 145: 103–115.',
    url: 'https://doi.org/10.1016/j.jpubeco.2016.10.002',
    year: 2017,
    theme: 'Compulsory voting & representation',
    summary: 'Exploits within-Austria variation in compulsory voting laws over time, finding compulsion raised turnout by roughly 10 points. Despite the turnout increase, they find little evidence of effects on the composition or size of government spending, a cautionary counterpoint to claims that turnout reliably reshapes policy.',
    contributions: [
      { topic: 'policy-approaches/compulsory-voting', note: 'clean causal estimate of compulsory voting\'s turnout effect in a developed democracy' },
      { topic: 'policy-approaches/overview', note: 'evidence that higher turnout does not always translate into measurable policy change' },
      { topic: 'key-debates/partisan-effects', note: 'tests and largely fails to find downstream fiscal/policy consequences of mandated turnout' },
    ],
  },
  {
    slug: 'miller-dassonneville-2016-high-turnout-low-countries',
    short: 'Miller & Dassonneville (2016)',
    title: 'Miller & Dassonneville (2016): High Turnout in the Low Countries',
    citation: 'Miller, Peter, and Ruth Dassonneville. 2016. "High Turnout in the Low Countries: Partisan Effects of the Abolition of Compulsory Voting in the Netherlands." Electoral Studies 44: 132–143.',
    url: 'https://doi.org/10.1016/j.electstud.2016.08.009',
    year: 2016,
    theme: 'Compulsory voting & representation',
    summary: 'Uses the 1970 abolition of compulsory voting in the Netherlands as a quasi-experiment to test whether high turnout benefits the left. Finds that compulsory voting (higher turnout) boosted Dutch social-democratic vote share while suppressing minor and extreme parties — qualified support for the conventional partisan-turnout hypothesis.',
    contributions: [
      { topic: 'key-debates/partisan-effects', note: 'quasi-experimental test of the "high turnout helps the left" claim' },
      { topic: 'policy-approaches/compulsory-voting', note: 'evidence on electoral consequences of removing a compulsory-voting regime' },
      { topic: 'key-debates/voluntary-vs-mandatory', note: 'documents who gains and loses when a country switches from mandatory to voluntary voting' },
    ],
  },
  {
    slug: 'ferwerda-2014-declining-participation-austria',
    short: 'Ferwerda (2014)',
    title: 'Ferwerda (2014): Electoral Consequences of Declining Participation',
    citation: 'Ferwerda, Jeremy. 2014. "Electoral Consequences of Declining Participation: A Natural Experiment in Austria." Electoral Studies 35: 242–252.',
    url: 'https://doi.org/10.1016/j.electstud.2014.01.010',
    year: 2014,
    theme: 'Compulsory voting & representation',
    summary: 'Leverages the staggered, non-voluntary repeal of compulsory voting across Austrian provinces to estimate how turnout decline affects party vote shares. Finds large turnout drops have only minimal partisan effects — the main shift is between minor and mainstream parties — challenging strong claims that turnout swings systematically advantage the left.',
    contributions: [
      { topic: 'key-debates/partisan-effects', note: 'natural-experiment evidence that turnout decline has minimal systematic partisan consequences' },
      { topic: 'policy-approaches/compulsory-voting', note: 'estimates electoral effects of abolishing compulsory voting' },
      { topic: 'policy-approaches/overview', note: 'tempers expectations that higher turnout reliably changes representation' },
    ],
  },
  {
    slug: 'jaitman-2013-causal-effect-compulsory-voting',
    short: 'Jaitman (2013)',
    title: 'Jaitman (2013): The Causal Effect of Compulsory Voting Laws',
    citation: 'Jaitman, Laura. 2013. "The Causal Effect of Compulsory Voting Laws on Turnout: Does Skill Matter?" Journal of Economic Behavior & Organization 92: 79–93.',
    url: 'https://doi.org/10.1016/j.jebo.2013.04.014',
    year: 2013,
    theme: 'Compulsory voting & representation',
    summary: 'Uses an age-based natural experiment to estimate compulsory voting\'s causal turnout effect, finding it raises turnout by ~18 points (28%), with the increase roughly twice as large for unskilled as for skilled citizens. Directly demonstrates that compulsory voting narrows the socioeconomic/skill gap in participation.',
    contributions: [
      { topic: 'policy-approaches/compulsory-voting', note: 'causal evidence that compulsion raises turnout and disproportionately mobilizes lower-skill citizens' },
      { topic: 'key-debates/voluntary-vs-mandatory', note: 'shows mandatory voting reduces class bias in participation, a core equality argument' },
      { topic: 'policy-approaches/overview', note: 'quantifies compulsory voting\'s effect on turnout inequality' },
    ],
  },
  {
    slug: 'chong-olivera-2008-compulsory-voting-equalize-incomes',
    short: 'Chong & Olivera (2008)',
    title: 'Chong & Olivera (2008): Does Compulsory Voting Help Equalize Incomes?',
    citation: 'Chong, Alberto, and Mauricio Olivera. 2008. "Does Compulsory Voting Help Equalize Incomes?" Economics & Politics 20(3): 391–415.',
    url: 'https://doi.org/10.1111/j.1468-0343.2008.00336.x',
    year: 2008,
    theme: 'Compulsory voting & representation',
    summary: 'Cross-country analysis of 91 countries (1960–2000) testing Lijphart\'s proposition that mandatory turnout reduces inequality. Finds that where compulsory voting is strongly enforced, income distribution improves (lower Gini, gains for bottom quintiles) — empirical support that turnout equality can feed into economic policy outcomes.',
    contributions: [
      { topic: 'policy-approaches/compulsory-voting', note: 'cross-national evidence linking enforced compulsory voting to lower income inequality' },
      { topic: 'key-debates/voluntary-vs-mandatory', note: 'supports the redistributive case for mandatory voting' },
      { topic: 'policy-approaches/overview', note: 'connects turnout inequality to policy/economic outcomes' },
    ],
  },
  {
    slug: 'hansford-gomez-2010-electoral-effects-turnout',
    short: 'Hansford & Gomez (2010)',
    title: 'Hansford & Gomez (2010): Estimating the Electoral Effects of Turnout',
    citation: 'Hansford, Thomas G., and Brad T. Gomez. 2010. "Estimating the Electoral Effects of Voter Turnout." American Political Science Review 104(2): 268–288.',
    url: 'https://doi.org/10.1017/S0003055410000109',
    year: 2010,
    theme: 'Compulsory voting & representation',
    summary: 'Uses Election Day rainfall as an instrument for turnout across U.S. counties (1948–2000 presidential elections) to break the endogeneity between turnout and vote choice. Finds higher turnout modestly aids Democrats, hurts incumbents, and makes outcomes more volatile/less predictable.',
    contributions: [
      { topic: 'key-debates/partisan-effects', note: 'instrumental-variable evidence on whether higher turnout benefits Democrats' },
      { topic: 'policy-approaches/overview', note: 'rigorous causal estimate of how turnout variation reshapes U.S. electoral outcomes' },
      { topic: 'policy-approaches/vote-by-mail-and-ballot-access', note: 'informs debate on whether turnout-raising reforms carry partisan consequences' },
    ],
  },
  {
    slug: 'martin-claibourn-2013-citizen-participation-responsiveness',
    short: 'Martin & Claibourn (2013)',
    title: 'Martin & Claibourn (2013): Citizen Participation and Congressional Responsiveness',
    citation: 'Martin, Paul S., and Michele P. Claibourn. 2013. "Citizen Participation and Congressional Responsiveness: New Evidence that Participation Matters." Legislative Studies Quarterly 38(1): 5–34.',
    url: 'https://doi.org/10.1111/lsq.12003',
    year: 2013,
    theme: 'Compulsory voting & representation',
    summary: 'Argues legislators read district turnout as a signal of scrutiny and sanction risk, so higher-participation districts receive greater policy responsiveness. Using nearly four decades of U.S. House data, finds districts with higher voting rates are rewarded with stronger congruence between representative behavior and constituent preferences.',
    contributions: [
      { topic: 'policy-approaches/overview', note: 'evidence that turnout levels causally shape legislative responsiveness and representation' },
      { topic: 'key-debates/partisan-effects', note: 'links participation inequality to unequal policy representation' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'shows aggregate participation (not just informed voting) drives representational outcomes' },
    ],
  },

  // ===== Theme 4: Civic education & youth =====
  {
    slug: 'campbell-2008-voice-in-the-classroom',
    short: 'Campbell (2008)',
    title: 'Campbell (2008): Voice in the Classroom',
    citation: 'Campbell, David E. 2008. "Voice in the Classroom: How an Open Classroom Climate Fosters Political Engagement Among Adolescents." Political Behavior 30(4): 437–454.',
    url: 'https://doi.org/10.1007/s11109-008-9063-z',
    year: 2008,
    theme: 'Civic education & youth',
    summary: 'Using the 1999 IEA CIVED survey of 9th-graders, Campbell shows that an open classroom climate (students feeling free to discuss and disagree about political/social issues) raises adolescents\' civic knowledge, appreciation of political conflict, and intention to vote as informed citizens. The effect partially compensates for low socioeconomic status, narrowing participation gaps.',
    contributions: [
      { topic: 'interventions/school-based-civic-education', note: 'evidence that classroom discussion climate, not just curriculum content, drives civic knowledge and anticipated participation' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'links open discussion to intention to be an informed voter, connecting knowledge and turnout dispositions' },
    ],
  },
  {
    slug: 'galston-2001-political-knowledge-engagement-civic-education',
    short: 'Galston (2001)',
    title: 'Galston (2001): Political Knowledge, Engagement, and Civic Education',
    citation: 'Galston, William A. 2001. "Political Knowledge, Political Engagement, and Civic Education." Annual Review of Political Science 4: 217–234.',
    url: 'https://doi.org/10.1146/annurev.polisci.4.1.217',
    year: 2001,
    theme: 'Civic education & youth',
    summary: 'A foundational review arguing that political knowledge matters (it shapes acceptance of democratic norms, issue attitudes, and participation) yet has stagnated despite rising formal education. Concludes that traditional classroom civic education can significantly raise political knowledge and that service learning is a promising complement.',
    contributions: [
      { topic: 'interventions/school-based-civic-education', note: 'canonical synthesis rehabilitating classroom civics as an effective knowledge-builder' },
      { topic: 'interventions/overview', note: 'frames why political knowledge is a target for interventions' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'centers political knowledge as distinct from and prerequisite to informed participation' },
    ],
  },
  {
    slug: 'holbein-hillygus-2020-making-young-voters',
    short: 'Holbein & Hillygus (2020)',
    title: 'Holbein & Hillygus (2020): Making Young Voters',
    citation: 'Holbein, John B., and D. Sunshine Hillygus. 2020. Making Young Voters: Converting Civic Attitudes into Civic Action. New York: Cambridge University Press.',
    url: 'https://doi.org/10.1017/9781108770446',
    year: 2020,
    theme: 'Civic education & youth',
    summary: 'Argues the youth turnout gap (roughly 28 points below over-60s in presidential years) stems not from apathy but from a follow-through gap: young people intend to vote but lack the noncognitive skills (self-regulation, persistence) to overcome registration and logistical hurdles. Recommends building noncognitive skills through civic education plus lowering barriers via preregistration and same-day registration.',
    contributions: [
      { topic: 'interventions/school-based-civic-education', note: 'reframes civic education toward noncognitive skill-building rather than knowledge alone' },
      { topic: 'policy-approaches/civic-education-mandates', note: 'motivates curricular reform as turnout policy' },
      { topic: 'policy-approaches/automatic-voter-registration', note: 'argues institutional barrier reduction converts intention into action' },
      { topic: 'key-debates/information-vs-mobilization', note: 'locates the youth problem in follow-through, not information or interest' },
    ],
  },
  {
    slug: 'holbein-hillygus-2016-preregistration-youth-turnout',
    short: 'Holbein & Hillygus (2016)',
    title: 'Holbein & Hillygus (2016): The Impact of Preregistration on Youth Turnout',
    citation: 'Holbein, John B., and D. Sunshine Hillygus. 2016. "Making Young Voters: The Impact of Preregistration on Youth Turnout." American Journal of Political Science 60(2): 364–382. (See also erratum, AJPS 2017.)',
    url: 'https://doi.org/10.1111/ajps.12177',
    year: 2016,
    theme: 'Civic education & youth',
    summary: 'Uses difference-in-differences and matching on CPS and Florida voter-file data to estimate that teen preregistration laws (allowing registration at 16/17) meaningfully increase youth turnout. Finds effects across subgroups and that preregistrants are not strongly tied to either party. (A 2017 erratum revised some estimates while preserving the positive turnout conclusion.)',
    contributions: [
      { topic: 'policy-approaches/automatic-voter-registration', note: 'core evidence that early/preregistration policy boosts youth turnout' },
      { topic: 'policy-approaches/vote-by-mail-and-ballot-access', note: 'treats registration access as a lever on participation' },
      { topic: 'key-debates/partisan-effects', note: 'finds preregistration mobilizes youth without clear partisan tilt' },
    ],
  },
  {
    slug: 'sondheimer-green-2010-education-turnout-experiments',
    short: 'Sondheimer & Green (2010)',
    title: 'Sondheimer & Green (2010): Education and Voter Turnout',
    citation: 'Sondheimer, Rachel Milstein, and Donald P. Green. 2010. "Using Experiments to Estimate the Effects of Education on Voter Turnout." American Journal of Political Science 54(1): 174–189.',
    url: 'https://doi.org/10.1111/j.1540-5907.2009.00425.x',
    year: 2010,
    theme: 'Civic education & youth',
    summary: 'Reanalyzes three interventions that exogenously raised educational attainment (Perry Preschool, Tennessee STAR class-size, and I Have A Dream) and tracks subjects into adulthood. Finds that boosting educational attainment causally increases later voter turnout, supporting a genuine (not merely spurious) education–turnout link.',
    contributions: [
      { topic: 'interventions/school-based-civic-education', note: 'experimental evidence that education itself causally raises adult turnout' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'bears on whether education\'s effect is real versus a proxy for background' },
      { topic: 'interventions/overview', note: 'anchors the education-as-turnout-driver claim in experimental design' },
    ],
  },
  {
    slug: 'gerber-green-shachar-2003-voting-habit-forming',
    short: 'Gerber, Green & Shachar (2003)',
    title: 'Gerber, Green & Shachar (2003): Voting May Be Habit-Forming',
    citation: 'Gerber, Alan S., Donald P. Green, and Ron Shachar. 2003. "Voting May Be Habit-Forming: Evidence from a Randomized Field Experiment." American Journal of Political Science 47(3): 540–550.',
    url: 'https://doi.org/10.1111/1540-5907.00038',
    year: 2003,
    theme: 'Civic education & youth',
    summary: 'Randomized GOTV (mail and face-to-face canvassing) among ~25,000 registered voters before the 1998 election, then tracks turnout in 1999. Using the 1998 treatment as an instrument, estimates that voting in one election raises the probability of voting in the next by roughly 47 percentage points — strong evidence that turnout is habit-forming.',
    contributions: [
      { topic: 'key-debates/information-vs-mobilization', note: 'foundational habit-formation result underpinning why early mobilization compounds over time' },
      { topic: 'interventions/door-to-door-canvassing', note: 'canvassing as the mobilizing treatment with downstream persistence' },
      { topic: 'interventions/direct-mail', note: 'mail as an experimental treatment arm' },
      { topic: 'interventions/overview', note: 'establishes downstream/persistent returns to any turnout intervention' },
    ],
  },
  {
    slug: 'bhatti-hansen-wass-2016-first-time-boost',
    short: 'Bhatti, Hansen & Wass (2016)',
    title: 'Bhatti, Hansen & Wass (2016): The First-Time Boost',
    citation: 'Bhatti, Yosef, Kasper M. Hansen, and Hanna Wass. 2016. "First-Time Boost Beats Experience: The Effect of Past Eligibility on Turnout." Electoral Studies 41: 151–158.',
    url: 'https://doi.org/10.1016/j.electstud.2015.12.005',
    year: 2016,
    theme: 'Civic education & youth',
    summary: 'Using validated turnout data, shows that the youngest first-time-eligible voters actually turn out at higher rates than slightly older first-timers, because early voting occurs while youth are still embedded in parental/school social contexts. Supports lowering the voting age / early first experiences to seed lifelong voting habits.',
    contributions: [
      { topic: 'key-debates/information-vs-mobilization', note: 'social embeddedness at the first election as a mobilization mechanism for habit formation' },
      { topic: 'policy-approaches/overview', note: 'informs voting-age and timing-of-first-vote policy debates' },
      { topic: 'interventions/school-based-civic-education', note: 'supports school/home context as a springboard for first-vote habit formation' },
    ],
  },
  {
    slug: 'neundorf-niemi-smets-2016-compensation-effect-civic-education',
    short: 'Neundorf, Niemi & Smets (2016)',
    title: 'Neundorf, Niemi & Smets (2016): The Compensation Effect of Civic Education',
    citation: 'Neundorf, Anja, Richard G. Niemi, and Kaat Smets. 2016. "The Compensation Effect of Civic Education on Political Engagement: How Civics Classes Make Up for Missing Parental Socialization." Political Behavior 38(4): 921–949.',
    url: 'https://doi.org/10.1007/s11109-016-9341-0',
    year: 2016,
    theme: 'Civic education & youth',
    summary: 'Using the U.S. Youth-Parent Socialization Panel (1965–1997) and the Belgian Political Panel (2006–2011), finds that civics coursework compensates for weak parental political socialization, raising engagement most for youth from low-politicization homes. The equalizing effect holds across two countries and eras.',
    contributions: [
      { topic: 'interventions/school-based-civic-education', note: 'evidence that civics classes reduce inequality in political engagement' },
      { topic: 'policy-approaches/civic-education-mandates', note: 'supports mandated civics as an equity lever' },
      { topic: 'key-debates/information-vs-mobilization', note: 'civic education as a compensatory socialization channel' },
    ],
  },
  {
    slug: 'meirick-wackman-2004-kids-voting-political-knowledge',
    short: 'Meirick & Wackman (2004)',
    title: 'Meirick & Wackman (2004): Kids Voting and Political Knowledge',
    citation: 'Meirick, Patrick C., and Daniel B. Wackman. 2004. "Kids Voting and Political Knowledge: Narrowing Gaps, Informing Votes." Social Science Quarterly 85(5): 1161–1177.',
    url: 'https://doi.org/10.1111/j.0038-4941.2004.00269.x',
    year: 2004,
    theme: 'Civic education & youth',
    summary: 'Evaluates the Kids Voting USA program (classroom curriculum culminating in a student mock election on Election Day) and finds it raises students\' political knowledge, partly by stimulating news attention and family political discussion. The program narrows knowledge gaps and supports more informed voting.',
    contributions: [
      { topic: 'interventions/school-based-civic-education', note: 'evidence that mock-election/action-civics curricula build knowledge and spur family discussion' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'shows a school program improving informedness, not just turnout' },
      { topic: 'interventions/voter-guides-and-information', note: 'curriculum functions as an information/engagement stimulus' },
    ],
  },
  {
    slug: 'kam-palmer-2008-reconsidering-education-participation',
    short: 'Kam & Palmer (2008)',
    title: 'Kam & Palmer (2008): Reconsidering the Effects of Education on Participation',
    citation: 'Kam, Cindy D., and Carl L. Palmer. 2008. "Reconsidering the Effects of Education on Political Participation." The Journal of Politics 70(3): 612–631.',
    url: 'https://doi.org/10.1017/S0022381608080651',
    year: 2008,
    theme: 'Civic education & youth',
    summary: 'Using propensity-score matching on the 1965–1997 Youth-Parent Socialization Panel, argues that once preadult experiences and family background are accounted for, higher education has little independent causal effect on participation — education is largely a proxy for earlier socialization. The influential skeptical counterpoint to the education-causes-participation consensus. (Later work, e.g. Henderson & Chatfield, contests these results.)',
    contributions: [
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'central skeptical position on whether education itself causes participation' },
      { topic: 'interventions/school-based-civic-education', note: 'cautions that observed education effects may reflect pre-adult socialization, motivating earlier interventions' },
      { topic: 'interventions/overview', note: 'frames the causal-identification debate over education and turnout' },
    ],
  },
  {
    slug: 'circle-2022-growing-voters',
    short: 'CIRCLE (2022)',
    title: 'CIRCLE (2022): Growing Voters',
    citation: 'Center for Information and Research on Civic Learning and Engagement (CIRCLE), Tisch College, Tufts University. 2022. Growing Voters: Building Institutions and Community Ecosystems for Equitable Election Participation. Medford, MA: Tufts University.',
    url: 'https://circle.tufts.edu/latest-research/growing-voters-engaging-youth-they-reach-voting-age-strengthen-democracy',
    year: 2022,
    theme: 'Civic education & youth',
    summary: 'CIRCLE\'s flagship report introduces the "Growing Voters" framework, arguing that youth turnout depends on engaging young people (including pre-voting-age) across schools, families, communities, and election institutions. Documents that mandatory, well-supported K–12 civics and school-based voter registration boost civic knowledge and engagement without producing partisanship.',
    contributions: [
      { topic: 'interventions/school-based-civic-education', note: 'synthesizes evidence and best practices for effective school civics and in-school registration' },
      { topic: 'policy-approaches/civic-education-mandates', note: 'supports statewide mandated civics as youth-turnout infrastructure' },
      { topic: 'policy-approaches/overview', note: 'ecosystem framework spanning schools, community, and election administration' },
      { topic: 'key-debates/partisan-effects', note: 'reports civic education improves engagement without increasing partisanship' },
    ],
  },

  // ===== Theme 5: Information & vote choice =====
  {
    slug: 'delli-carpini-keeter-1996-what-americans-know',
    short: 'Delli Carpini & Keeter (1996)',
    title: 'Delli Carpini & Keeter (1996): What Americans Know About Politics',
    citation: 'Delli Carpini, Michael X., and Scott Keeter. 1996. What Americans Know about Politics and Why It Matters. New Haven, CT: Yale University Press.',
    url: 'https://www.jstor.org/stable/j.ctt1cc2kv1',
    year: 1996,
    theme: 'Information & vote choice',
    summary: 'The most comprehensive analysis of the level and distribution of political knowledge in the U.S. public, drawing on decades of survey data. Finds knowledge is low on average and highly unequally distributed (by race, gender, age, and income), and that better-informed citizens participate more, better identify their own interests, and connect preferences to political action.',
    contributions: [
      { topic: 'interventions/voter-guides-and-information', note: 'foundational evidence that political knowledge shapes whether citizens can identify and act on their interests' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'documents that the informed both participate more and vote more consistently with their interests' },
      { topic: 'policy-approaches/civic-education-mandates', note: 'inequality in knowledge underpins the case for civic education to close information gaps' },
    ],
  },
  {
    slug: 'bartels-1996-uninformed-votes',
    short: 'Bartels (1996)',
    title: 'Bartels (1996): Uninformed Votes',
    citation: 'Bartels, Larry M. 1996. "Uninformed Votes: Information Effects in Presidential Elections." American Journal of Political Science 40(1): 194–230.',
    url: 'https://www.jstor.org/stable/2111700',
    year: 1996,
    theme: 'Information & vote choice',
    summary: 'Uses 1972–1992 ANES data to simulate how vote choices would differ if voters were "fully informed," matching informed and uninformed voters with similar demographics. Finds substantial information effects: cues/shortcuts do not fully compensate for low information, and individual deviations do not cancel out in the aggregate, so incumbents and Democrats were systematically advantaged by low information.',
    contributions: [
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'central evidence that information changes vote choice, challenging "low-information rationality"' },
      { topic: 'interventions/voter-guides-and-information', note: 'quantifies the electoral stakes of voter information deficits' },
      { topic: 'key-debates/partisan-effects', note: 'shows information effects can systematically favor particular parties/candidates' },
    ],
  },
  {
    slug: 'lau-redlawsk-1997-voting-correctly',
    short: 'Lau & Redlawsk (1997)',
    title: 'Lau & Redlawsk (1997): Voting Correctly',
    citation: 'Lau, Richard R., and David P. Redlawsk. 1997. "Voting Correctly." American Political Science Review 91(3): 585–598.',
    url: 'https://doi.org/10.2307/2952076',
    year: 1997,
    theme: 'Information & vote choice',
    summary: 'Introduces the concept of "correct voting" — voting the way one would have with full information — and offers two methods for measuring it (a normative fully-informed-preferences benchmark and a process-tracing experimental benchmark). Finds roughly 75% of voters vote correctly, an optimistic counterpoint to the pessimistic knowledge literature.',
    contributions: [
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'defines the "correct voting" standard for whether votes match voters\' informed preferences' },
      { topic: 'interventions/voter-guides-and-information', note: 'establishes the outcome metric (correct voting) that information interventions aim to improve' },
      { topic: 'key-debates/information-vs-mobilization', note: 'reframes democratic competence around decision quality rather than knowledge quantity' },
    ],
  },
  {
    slug: 'lau-redlawsk-2001-cognitive-heuristics',
    short: 'Lau & Redlawsk (2001)',
    title: 'Lau & Redlawsk (2001): Cognitive Heuristics in Political Decision Making',
    citation: 'Lau, Richard R., and David P. Redlawsk. 2001. "Advantages and Disadvantages of Cognitive Heuristics in Political Decision Making." American Journal of Political Science 45(4): 951–971.',
    url: 'https://www.jstor.org/stable/2669334',
    year: 2001,
    theme: 'Information & vote choice',
    summary: 'Uses a dynamic process-tracing experiment in a mock presidential campaign to test whether five common heuristics (party, ideology, endorsements, polls, candidate appearance) actually improve voter decisions. Finds heuristics help political experts vote correctly but can hurt low-knowledge voters, challenging the assumption that cues let uninformed voters behave as if informed.',
    contributions: [
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'shows heuristics do not reliably substitute for information, especially for the less informed' },
      { topic: 'interventions/voter-guides-and-information', note: 'implies simplified cues are not a costless replacement for substantive information' },
      { topic: 'key-debates/partisan-effects', note: 'party/ideology cues have uneven effects on decision quality across voter types' },
    ],
  },
  {
    slug: 'lau-andersen-redlawsk-2008-exploration-correct-voting',
    short: 'Lau, Andersen & Redlawsk (2008)',
    title: 'Lau, Andersen & Redlawsk (2008): An Exploration of Correct Voting',
    citation: 'Lau, Richard R., David J. Andersen, and David P. Redlawsk. 2008. "An Exploration of Correct Voting in Recent U.S. Presidential Elections." American Journal of Political Science 52(2): 395–411.',
    url: 'https://doi.org/10.1111/j.1540-5907.2008.00319.x',
    year: 2008,
    theme: 'Information & vote choice',
    summary: 'Applies the fully-informed-preferences method to nine U.S. presidential elections (1972–2004) using ANES data. Finds an average of just over three-quarters of voters voted correctly, and identifies campaign- and individual-level factors (e.g., information availability, campaign clarity) that raise or lower correct-voting rates.',
    contributions: [
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'provides over-time estimates of how well votes match informed preferences' },
      { topic: 'interventions/voter-guides-and-information', note: 'links the information environment to correct-voting rates' },
      { topic: 'interventions/overview', note: 'identifies contextual factors that improve vote quality, relevant to intervention design' },
    ],
  },
  {
    slug: 'achen-bartels-2016-democracy-for-realists',
    short: 'Achen & Bartels (2016)',
    title: 'Achen & Bartels (2016): Democracy for Realists',
    citation: 'Achen, Christopher H., and Larry M. Bartels. 2016. Democracy for Realists: Why Elections Do Not Produce Responsive Government. Princeton, NJ: Princeton University Press.',
    url: 'https://press.princeton.edu/books/hardcover/9780691169446/democracy-for-realists',
    year: 2016,
    theme: 'Information & vote choice',
    summary: 'Attacks the "folk theory" of democracy, arguing that voters (even informed ones) choose based on social identities and partisan loyalties rather than issues or retrospective performance, and that they rationalize facts to fit those loyalties. Directly critiques the "miracle of aggregation" and the idea that information or cues rescue collective competence.',
    contributions: [
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'argues information does little to change identity-driven vote choice, a skeptical bookend to the correct-voting literature' },
      { topic: 'key-debates/partisan-effects', note: 'centers partisan/group identity as the driver of vote choice' },
      { topic: 'key-debates/information-vs-mobilization', note: 'questions whether informing voters meaningfully changes outcomes' },
    ],
  },
  {
    slug: 'lassen-2005-information-voter-turnout',
    short: 'Lassen (2005)',
    title: 'Lassen (2005): The Effect of Information on Voter Turnout',
    citation: 'Lassen, David Dreyer. 2005. "The Effect of Information on Voter Turnout: Evidence from a Natural Experiment." American Journal of Political Science 49(1): 103–118.',
    url: 'https://doi.org/10.1111/j.0092-5853.2005.00113.x',
    year: 2005,
    theme: 'Information & vote choice',
    summary: 'Exploits a Copenhagen decentralization pilot in which four representative districts were assigned local administration while others were not, then compares turnout in a citywide referendum. Finds that being informed (through direct experience with the treated policy) causally increased turnout, giving rare quasi-experimental evidence that information boosts participation.',
    contributions: [
      { topic: 'key-debates/information-vs-mobilization', note: 'causal evidence that information itself raises turnout, not just vote choice' },
      { topic: 'interventions/voter-guides-and-information', note: 'supports information provision as a turnout lever' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'connects the information environment to participation' },
    ],
  },
  {
    slug: 'larcinese-2007-political-knowledge-turnout',
    short: 'Larcinese (2007)',
    title: 'Larcinese (2007): Does Political Knowledge Increase Turnout?',
    citation: 'Larcinese, Valentino. 2007. "Does Political Knowledge Increase Turnout? Evidence from the 1997 British General Election." Public Choice 131(3–4): 387–411.',
    url: 'https://doi.org/10.1007/s11127-006-9122-0',
    year: 2007,
    theme: 'Information & vote choice',
    summary: 'Uses 1997 British Election Study data and instrumental-variable strategies to estimate the effect of political knowledge on turnout. Finds information is among the strongest predictors of participation — raising knowledge one standard deviation increases the probability of voting by roughly 6 percentage points — while addressing endogeneity between knowledge and voting.',
    contributions: [
      { topic: 'key-debates/information-vs-mobilization', note: 'quantifies political knowledge as a major driver of turnout' },
      { topic: 'interventions/voter-guides-and-information', note: 'motivates information-based interventions to raise participation' },
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'links knowledge to the decision to vote' },
    ],
  },
  {
    slug: 'garzia-marschall-2012-vaa-state-of-research',
    short: 'Garzia & Marschall (2012)',
    title: 'Garzia & Marschall (2012): Voting Advice Applications Under Review',
    citation: 'Garzia, Diego, and Stefan Marschall. 2012. "Voting Advice Applications Under Review: The State of Research." International Journal of Electronic Governance 5(3/4): 203–222.',
    url: 'https://doi.org/10.1504/IJEG.2012.051309',
    year: 2012,
    theme: 'Information & vote choice',
    summary: 'Reviews and maps the research literature on voting advice applications (VAAs) — online tools that match users\' issue positions to parties/candidates — and sets out a comparative research agenda. Synthesizes evidence on why VAAs spread across Europe and their emerging effects on political knowledge, turnout, and vote choice.',
    contributions: [
      { topic: 'interventions/voter-guides-and-information', note: 'foundational review of VAAs as a scalable information/matching intervention' },
      { topic: 'key-debates/information-vs-mobilization', note: 'surveys VAA effects on both informing voters and mobilizing turnout' },
      { topic: 'interventions/digital-and-social-media-ads', note: 'situates VAAs within online political information tools' },
    ],
  },
  {
    slug: 'gemenis-rosema-2014-vaa-electoral-turnout',
    short: 'Gemenis & Rosema (2014)',
    title: 'Gemenis & Rosema (2014): Voting Advice Applications and Turnout',
    citation: 'Gemenis, Kostas, and Martin Rosema. 2014. "Voting Advice Applications and Electoral Turnout." Electoral Studies 36: 281–289.',
    url: 'https://doi.org/10.1016/j.electstud.2014.06.010',
    year: 2014,
    theme: 'Information & vote choice',
    summary: 'Uses Dutch survey data and selection-into-treatment (matching/propensity) methods to isolate the causal effect of VAA usage on turnout, addressing self-selection problems in earlier work. Estimates that VAA use accounted for about four percent of reported turnout, evidence that these information tools modestly raise participation.',
    contributions: [
      { topic: 'interventions/voter-guides-and-information', note: 'quasi-causal evidence that a voter-information tool increases turnout' },
      { topic: 'key-debates/information-vs-mobilization', note: 'shows an information intervention can double as a mobilization tool' },
      { topic: 'interventions/digital-and-social-media-ads', note: 'evaluates a digital tool\'s effect on participation' },
    ],
  },
  {
    slug: 'page-shapiro-1992-rational-public',
    short: 'Page & Shapiro (1992)',
    title: 'Page & Shapiro (1992): The Rational Public',
    citation: 'Page, Benjamin I., and Robert Y. Shapiro. 1992. The Rational Public: Fifty Years of Trends in Americans\' Policy Preferences. Chicago: University of Chicago Press.',
    url: 'https://press.uchicago.edu/ucp/books/book/chicago/R/bo3762628.html',
    year: 1992,
    theme: 'Information & vote choice',
    summary: 'Analyzes fifty years of U.S. public-opinion survey trends and argues that, although individuals are poorly informed, collective public opinion is stable, coherent, and responds sensibly to new events and information. A key statement of the "miracle of aggregation" — that individual errors cancel out, yielding a rational aggregate public.',
    contributions: [
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'articulates the aggregation argument that collective opinion can be competent despite individual ignorance' },
      { topic: 'interventions/voter-guides-and-information', note: 'frames how information moves collective (not just individual) preferences' },
      { topic: 'key-debates/information-vs-mobilization', note: 'foundational reference for whether informing individuals matters at the aggregate level' },
    ],
  },
  {
    slug: 'converse-1990-popular-representation-information',
    short: 'Converse (1990)',
    title: 'Converse (1990): Popular Representation and the Distribution of Information',
    citation: 'Converse, Philip E. 1990. "Popular Representation and the Distribution of Information." In Information and Democratic Processes, ed. John A. Ferejohn and James H. Kuklinski. Urbana: University of Illinois Press, pp. 369–388.',
    url: 'https://www.google.com/books/edition/Information_and_Democratic_Processes/hd6-AAAAIAAJ',
    year: 1990,
    theme: 'Information & vote choice',
    summary: 'Examines how political information is distributed across the electorate and coined the "miracle of aggregation" — the idea that random errors by low-information citizens cancel out so that aggregate opinion reflects the views of the informed. A canonical source for the aggregation defense of mass democratic competence later contested by Bartels and Achen & Bartels.',
    contributions: [
      { topic: 'key-debates/informed-voting-vs-turnout', note: 'origin of the "miracle of aggregation" concept central to debates on voter competence' },
      { topic: 'interventions/voter-guides-and-information', note: 'frames the theoretical stakes of unequal information distribution' },
      { topic: 'key-debates/information-vs-mobilization', note: 'grounds whether individual-level information matters given aggregation' },
    ],
  },

  // ===== Theme 6: Registration, access & partisan effects =====
  {
    slug: 'thompson-2020-universal-vote-by-mail-no-partisan-effect',
    short: 'Thompson et al. (2020)',
    title: 'Thompson et al. (2020): Universal Vote-by-Mail Has No Partisan Effect',
    citation: 'Thompson, Daniel M., Jennifer A. Wu, Jesse Yoder, and Andrew B. Hall. 2020. "Universal Vote-by-Mail Has No Impact on Partisan Turnout or Vote Share." Proceedings of the National Academy of Sciences 117(25): 14052–14056.',
    url: 'https://doi.org/10.1073/pnas.2007249117',
    year: 2020,
    theme: 'Registration, access & partisan effects',
    summary: 'Using a difference-in-differences design on county-level data from states that rolled out universal vote-by-mail (every voter automatically mailed a ballot), the authors estimate its causal effects. They find UVBM modestly raises overall turnout (roughly 2 percentage points) but has no detectable effect on either party\'s share of turnout or vote share, contradicting claims that VBM advantages Democrats.',
    contributions: [
      { topic: 'policy-approaches/vote-by-mail-and-ballot-access', note: 'causal evidence that universal VBM raises turnout slightly without changing who wins' },
      { topic: 'key-debates/partisan-effects', note: 'strong evidence that a major convenience-voting reform is partisan-neutral' },
    ],
  },
  {
    slug: 'leighley-nagler-2013-who-votes-now',
    short: 'Leighley & Nagler (2013)',
    title: 'Leighley & Nagler (2013): Who Votes Now?',
    citation: 'Leighley, Jan E., and Jonathan Nagler. 2013. Who Votes Now? Demographics, Issues, Inequality, and Turnout in the United States. Princeton, NJ: Princeton University Press.',
    url: 'https://press.princeton.edu/books/paperback/9780691159355/who-votes-now',
    year: 2013,
    theme: 'Registration, access & partisan effects',
    summary: 'Drawing on Census CPS and ANES data from 1972–2008, compares the demographic profiles and policy preferences of voters versus nonvoters. Documents a persistent class bias (the rich vote more than the poor, and voters are more economically conservative than nonvoters), a closed black-white gap, and shows that reforms like Election Day registration and easier absentee/early voting boost turnout.',
    contributions: [
      { topic: 'policy-approaches/automatic-voter-registration', note: 'evidence that registration-easing reforms (especially Election Day registration) raise turnout' },
      { topic: 'policy-approaches/vote-by-mail-and-ballot-access', note: 'assesses absentee/early voting effects on turnout' },
      { topic: 'key-debates/partisan-effects', note: 'documents systematic preference differences between voters and nonvoters' },
    ],
  },
  {
    slug: 'denardo-1980-turnout-and-the-vote',
    short: 'DeNardo (1980)',
    title: "DeNardo (1980): Turnout and the Vote — The Joke's on the Democrats?",
    citation: 'DeNardo, James. 1980. "Turnout and the Vote: The Joke\'s on the Democrats?" American Political Science Review 74(2): 406–420.',
    url: 'https://doi.org/10.2307/1960636',
    year: 1980,
    theme: 'Registration, access & partisan effects',
    summary: 'A foundational theoretical and empirical challenge to the conventional wisdom that high turnout helps Democrats. DeNardo argues that surge voters are more likely to defect from their nominal party ties, so higher turnout brings in "peripheral" voters whose defection can benefit the minority party, meaning increased turnout does not reliably advantage Democrats.',
    contributions: [
      { topic: 'key-debates/partisan-effects', note: 'the classic statement questioning whether higher turnout benefits the left' },
    ],
  },
  {
    slug: 'burden-2014-election-laws-mobilization-turnout',
    short: 'Burden et al. (2014)',
    title: 'Burden et al. (2014): Election Laws, Mobilization, and Turnout',
    citation: 'Burden, Barry C., David T. Canon, Kenneth R. Mayer, and Donald P. Moynihan. 2014. "Election Laws, Mobilization, and Turnout: The Unanticipated Consequences of Election Reform." American Journal of Political Science 58(1): 95–109.',
    url: 'https://doi.org/10.1111/ajps.12063',
    year: 2014,
    theme: 'Registration, access & partisan effects',
    summary: 'Using aggregate and individual-level analyses of the 2004 and 2008 elections, shows Election Day (same-day) registration consistently raises turnout, whereas early voting by itself is associated with lower turnout because it dissipates the mobilizing energy of Election Day. Combining early voting with same-day registration offsets the negative effect.',
    contributions: [
      { topic: 'policy-approaches/vote-by-mail-and-ballot-access', note: 'early voting alone can reduce turnout absent complementary reforms' },
      { topic: 'policy-approaches/automatic-voter-registration', note: 'same-day/Election Day registration reliably increases turnout' },
      { topic: 'key-debates/information-vs-mobilization', note: 'reforms interact with campaign mobilization, sometimes perversely' },
    ],
  },
  {
    slug: 'grumbach-hill-2022-rock-the-registration',
    short: 'Grumbach & Hill (2022)',
    title: 'Grumbach & Hill (2022): Same Day Registration and Youth Turnout',
    citation: 'Grumbach, Jacob M., and Charlotte Hill. 2022. "Rock the Registration: Same Day Registration Increases Turnout of Young Voters." The Journal of Politics 84(1): 405–417.',
    url: 'https://doi.org/10.1086/714776',
    year: 2022,
    theme: 'Registration, access & partisan effects',
    summary: 'Using a difference-in-differences design across states adopting same-day registration (SDR), estimates registration-reform effects by age. Finds SDR increases turnout among 18–24-year-olds in presidential elections by roughly 3–7 percentage points, a substantially larger effect than for older voters, indicating registration barriers disproportionately depress youth participation.',
    contributions: [
      { topic: 'policy-approaches/automatic-voter-registration', note: 'same-day registration strongly boosts youth turnout' },
      { topic: 'key-debates/partisan-effects', note: 'reforms that add young registrants can shift electorate composition' },
    ],
  },
  {
    slug: 'gronke-2008-convenience-voting',
    short: 'Gronke et al. (2008)',
    title: 'Gronke et al. (2008): Convenience Voting',
    citation: 'Gronke, Paul, Eva Galanes-Rosenbaum, Peter A. Miller, and Daniel Toffey. 2008. "Convenience Voting." Annual Review of Political Science 11: 437–455.',
    url: 'https://doi.org/10.1146/annurev.polisci.11.053006.190912',
    year: 2008,
    theme: 'Registration, access & partisan effects',
    summary: 'A synthesizing review of "convenience voting" modes (early in-person, vote-by-mail, absentee, electronic), which by then accounted for over 30% of ballots. Concludes that convenience reforms mostly retain existing voters rather than mobilize new ones, and that all-mail elections show the most consistent (if modest) turnout gains.',
    contributions: [
      { topic: 'policy-approaches/vote-by-mail-and-ballot-access', note: 'review of how convenience-voting modes affect turnout' },
      { topic: 'policy-approaches/overview', note: 'framework for classifying ballot-access reforms' },
      { topic: 'key-debates/partisan-effects', note: 'evidence that convenience reforms mostly retain, not add, voters' },
    ],
  },
  {
    slug: 'citrin-schickler-sides-2003-what-if-everyone-voted',
    short: 'Citrin, Schickler & Sides (2003)',
    title: 'Citrin, Schickler & Sides (2003): What If Everyone Voted?',
    citation: 'Citrin, Jack, Eric Schickler, and John Sides. 2003. "What If Everyone Voted? Simulating the Impact of Increased Turnout in Senate Elections." American Journal of Political Science 47(1): 75–90.',
    url: 'https://doi.org/10.1111/1540-5907.00006',
    year: 2003,
    theme: 'Registration, access & partisan effects',
    summary: 'Using state exit-poll and Census data, estimates nonvoters\' partisan preferences and simulates Senate election outcomes under universal turnout. Although nonvoters lean somewhat more Democratic, so few races are close that virtually no outcomes would flip, undercutting the claim that full turnout would systematically help Democrats.',
    contributions: [
      { topic: 'key-debates/partisan-effects', note: 'simulation evidence that full turnout would rarely change who wins' },
      { topic: 'key-debates/voluntary-vs-mandatory', note: 'informs debates over compulsory/universal turnout consequences' },
    ],
  },
  {
    slug: 'highton-2004-voter-registration-and-turnout',
    short: 'Highton (2004)',
    title: 'Highton (2004): Voter Registration and Turnout in the United States',
    citation: 'Highton, Benjamin. 2004. "Voter Registration and Turnout in the United States." Perspectives on Politics 2(3): 507–515.',
    url: 'https://doi.org/10.1017/S1537592704040307',
    year: 2004,
    theme: 'Registration, access & partisan effects',
    summary: 'A review essay tracing how U.S. registration laws (from the late 19th century through the 2000s) shape turnout levels, which groups are most affected, and the partisan implications. Concludes registration barriers depress turnout, especially among lower-status citizens, but that easing them yields smaller partisan effects than commonly assumed.',
    contributions: [
      { topic: 'policy-approaches/automatic-voter-registration', note: 'synthesis of how registration requirements suppress turnout' },
      { topic: 'policy-approaches/overview', note: 'historical framing of registration as a turnout barrier' },
      { topic: 'key-debates/partisan-effects', note: 'assesses the partisan stakes of registration reform' },
    ],
  },
  {
    slug: 'hajnal-trounstine-2005-where-turnout-matters',
    short: 'Hajnal & Trounstine (2005)',
    title: 'Hajnal & Trounstine (2005): Where Turnout Matters',
    citation: 'Hajnal, Zoltan L., and Jessica Trounstine. 2005. "Where Turnout Matters: The Consequences of Uneven Turnout in City Politics." The Journal of Politics 67(2): 515–535.',
    url: 'https://doi.org/10.1111/j.1468-2508.2005.00327.x',
    year: 2005,
    theme: 'Registration, access & partisan effects',
    summary: 'Arguing that national-election studies understate turnout bias, examines local elections and finds that low and uneven turnout substantially reduces the representation of Latinos and Asian Americans on city councils and in mayoralties. Shows that who votes can meaningfully change who governs where minority populations are pivotal.',
    contributions: [
      { topic: 'key-debates/partisan-effects', note: 'evidence that uneven turnout biases representation (racial/ethnic composition effects)' },
      { topic: 'policy-approaches/overview', note: 'motivates reforms addressing turnout inequality in local elections' },
    ],
  },
  {
    slug: 'nickerson-2015-voter-registration-drives',
    short: 'Nickerson (2015)',
    title: 'Nickerson (2015): Do Voter Registration Drives Increase Participation?',
    citation: 'Nickerson, David W. 2015. "Do Voter Registration Drives Increase Participation? For Whom and When?" The Journal of Politics 77(1): 88–101.',
    url: 'https://doi.org/10.1086/678391',
    year: 2015,
    theme: 'Registration, access & partisan effects',
    summary: 'Using field experiments across six cities in which 620 streets were randomly assigned to receive door-to-door registration canvassing, isolates the causal effect of registration drives free of self-selection. Finds drives add genuinely new voters to the electorate (rather than merely processing people who would have registered anyway), with effects concentrated among lower-propensity individuals.',
    contributions: [
      { topic: 'interventions/door-to-door-canvassing', note: 'experimental evidence that registration canvassing adds new voters' },
      { topic: 'policy-approaches/automatic-voter-registration', note: 'clarifies how much registration barriers, not just motivation, limit participation' },
      { topic: 'key-debates/information-vs-mobilization', note: 'mobilizing registration produces net new participation' },
    ],
  },
  {
    slug: 'mcghee-hill-romero-2021-registration-turnout-effects-of-avr',
    short: 'McGhee, Hill & Romero (2021)',
    title: 'McGhee, Hill & Romero (2021): The Registration and Turnout Effects of AVR',
    citation: 'McGhee, Eric, Charlotte Hill, and Mindy Romero. 2021. "The Registration and Turnout Effects of Automatic Voter Registration." SSRN Working Paper No. 3933442 (USC CCEP / PPIC).',
    url: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3933442',
    year: 2021,
    theme: 'Registration, access & partisan effects',
    summary: 'Using a difference-in-differences design across states, this systematic study of automatic voter registration (AVR) design finds effects depend heavily on implementation. Back-end default AVR raised registration by about 8.1% and eligible turnout by about 3.3%; front-end default raised registration ~2.9% and turnout ~1.1%. AVR adds many registrants who are individually less likely to vote, yet enough do that overall eligible turnout still rises. (Working paper.)',
    contributions: [
      { topic: 'policy-approaches/automatic-voter-registration', note: 'direct evidence that AVR raises registration and turnout, with design (back-end default) mattering most' },
      { topic: 'policy-approaches/overview', note: 'shows reform-design details drive turnout outcomes' },
    ],
  },
];
